sonar.projectKey=b12705030_TSMC_PMD
sonar.organization=b12705030

sonar.sources=frontend/src,backend/src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/*.test.ts,**/dist/**,**/.next/**,**/prisma/**
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.coverage.exclusions=frontend/**
sonar.sourceEncoding=UTF-8
